spring:
  datasource:
    url: jdbc:mysql://localhost:3306/psm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #    加上问号后面的防止数据库防止乱码
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  typeAliasesPackage: whu.web.psm.*.pojo
  mapperLocations: classpath*:mapper/**/*.xml
server:
  port: 8080
