package whu.web.psm.pojo;

import java.util.Date;

public class MissionTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.post_time
     *
     * @mbggenerated
     */
    private Date postTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.label1
     *
     * @mbggenerated
     */
    private String label1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.label2
     *
     * @mbggenerated
     */
    private String label2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.label3
     *
     * @mbggenerated
     */
    private String label3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column missiontable.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.mid
     *
     * @return the value of missiontable.mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.mid
     *
     * @param mid the value for missiontable.mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.title
     *
     * @return the value of missiontable.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.title
     *
     * @param title the value for missiontable.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.post_time
     *
     * @return the value of missiontable.post_time
     *
     * @mbggenerated
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.post_time
     *
     * @param postTime the value for missiontable.post_time
     *
     * @mbggenerated
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.end_time
     *
     * @return the value of missiontable.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.end_time
     *
     * @param endTime the value for missiontable.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.state
     *
     * @return the value of missiontable.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.state
     *
     * @param state the value for missiontable.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.money
     *
     * @return the value of missiontable.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.money
     *
     * @param money the value for missiontable.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.label1
     *
     * @return the value of missiontable.label1
     *
     * @mbggenerated
     */
    public String getLabel1() {
        return label1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.label1
     *
     * @param label1 the value for missiontable.label1
     *
     * @mbggenerated
     */
    public void setLabel1(String label1) {
        this.label1 = label1 == null ? null : label1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.label2
     *
     * @return the value of missiontable.label2
     *
     * @mbggenerated
     */
    public String getLabel2() {
        return label2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.label2
     *
     * @param label2 the value for missiontable.label2
     *
     * @mbggenerated
     */
    public void setLabel2(String label2) {
        this.label2 = label2 == null ? null : label2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.label3
     *
     * @return the value of missiontable.label3
     *
     * @mbggenerated
     */
    public String getLabel3() {
        return label3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.label3
     *
     * @param label3 the value for missiontable.label3
     *
     * @mbggenerated
     */
    public void setLabel3(String label3) {
        this.label3 = label3 == null ? null : label3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.comment
     *
     * @return the value of missiontable.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.comment
     *
     * @param comment the value for missiontable.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column missiontable.description
     *
     * @return the value of missiontable.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column missiontable.description
     *
     * @param description the value for missiontable.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}