package whu.web.psm.pojo;

public class Mission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.change_number
     *
     * @mbggenerated
     */
    private Integer changeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.deadline
     *
     * @mbggenerated
     */
    private String deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.existence_date
     *
     * @mbggenerated
     */
    private String existenceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.label1
     *
     * @mbggenerated
     */
    private String label1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.label2
     *
     * @mbggenerated
     */
    private String label2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.label3
     *
     * @mbggenerated
     */
    private String label3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.m_title
     *
     * @mbggenerated
     */
    private String mTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mission_info
     *
     * @mbggenerated
     */
    private String missionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.people_amount
     *
     * @mbggenerated
     */
    private Integer peopleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.publish_time
     *
     * @mbggenerated
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mid
     *
     * @return the value of mission.mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mid
     *
     * @param mid the value for mission.mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.change_number
     *
     * @return the value of mission.change_number
     *
     * @mbggenerated
     */
    public Integer getChangeNumber() {
        return changeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.change_number
     *
     * @param changeNumber the value for mission.change_number
     *
     * @mbggenerated
     */
    public void setChangeNumber(Integer changeNumber) {
        this.changeNumber = changeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.deadline
     *
     * @return the value of mission.deadline
     *
     * @mbggenerated
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.deadline
     *
     * @param deadline the value for mission.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline == null ? null : deadline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.existence_date
     *
     * @return the value of mission.existence_date
     *
     * @mbggenerated
     */
    public String getExistenceDate() {
        return existenceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.existence_date
     *
     * @param existenceDate the value for mission.existence_date
     *
     * @mbggenerated
     */
    public void setExistenceDate(String existenceDate) {
        this.existenceDate = existenceDate == null ? null : existenceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.file_name
     *
     * @return the value of mission.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.file_name
     *
     * @param fileName the value for mission.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.label1
     *
     * @return the value of mission.label1
     *
     * @mbggenerated
     */
    public String getLabel1() {
        return label1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.label1
     *
     * @param label1 the value for mission.label1
     *
     * @mbggenerated
     */
    public void setLabel1(String label1) {
        this.label1 = label1 == null ? null : label1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.label2
     *
     * @return the value of mission.label2
     *
     * @mbggenerated
     */
    public String getLabel2() {
        return label2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.label2
     *
     * @param label2 the value for mission.label2
     *
     * @mbggenerated
     */
    public void setLabel2(String label2) {
        this.label2 = label2 == null ? null : label2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.label3
     *
     * @return the value of mission.label3
     *
     * @mbggenerated
     */
    public String getLabel3() {
        return label3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.label3
     *
     * @param label3 the value for mission.label3
     *
     * @mbggenerated
     */
    public void setLabel3(String label3) {
        this.label3 = label3 == null ? null : label3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.m_title
     *
     * @return the value of mission.m_title
     *
     * @mbggenerated
     */
    public String getmTitle() {
        return mTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.m_title
     *
     * @param mTitle the value for mission.m_title
     *
     * @mbggenerated
     */
    public void setmTitle(String mTitle) {
        this.mTitle = mTitle == null ? null : mTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.mission_info
     *
     * @return the value of mission.mission_info
     *
     * @mbggenerated
     */
    public String getMissionInfo() {
        return missionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.mission_info
     *
     * @param missionInfo the value for mission.mission_info
     *
     * @mbggenerated
     */
    public void setMissionInfo(String missionInfo) {
        this.missionInfo = missionInfo == null ? null : missionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.money
     *
     * @return the value of mission.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.money
     *
     * @param money the value for mission.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.people_amount
     *
     * @return the value of mission.people_amount
     *
     * @mbggenerated
     */
    public Integer getPeopleAmount() {
        return peopleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.people_amount
     *
     * @param peopleAmount the value for mission.people_amount
     *
     * @mbggenerated
     */
    public void setPeopleAmount(Integer peopleAmount) {
        this.peopleAmount = peopleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.publish_time
     *
     * @return the value of mission.publish_time
     *
     * @mbggenerated
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.publish_time
     *
     * @param publishTime the value for mission.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.state
     *
     * @return the value of mission.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.state
     *
     * @param state the value for mission.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mission.uid
     *
     * @return the value of mission.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mission.uid
     *
     * @param uid the value for mission.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}