package whu.web.psm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import whu.web.psm.pojo.MissionTable;
import whu.web.psm.pojo.MissionTableExample;
import whu.web.psm.pojo.MissionTableWithBLOBs;

public interface MissionTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int countByExample(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int deleteByExample(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int insert(MissionTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int insertSelective(MissionTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    List<MissionTableWithBLOBs> selectByExampleWithBLOBs(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    List<MissionTable> selectByExample(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    MissionTableWithBLOBs selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MissionTableWithBLOBs record, @Param("example") MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MissionTableWithBLOBs record, @Param("example") MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MissionTable record, @Param("example") MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MissionTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MissionTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MissionTable record);
}