package whu.web.psm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import whu.web.psm.pojo.Mission;
import whu.web.psm.pojo.MissionExample;
public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int countByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int deleteByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int insert(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int insertSelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    List<Mission> selectByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    Mission selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mission record);
}