package whu.web.psm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import whu.web.psm.pojo.MissionTable;
import whu.web.psm.pojo.MissionTableExample;

@Mapper
public interface MissionTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int countByExample(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int deleteByExample(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int insert(MissionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int insertSelective(MissionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    List<MissionTable> selectByExampleWithBLOBs(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    List<MissionTable> selectByExample(MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    MissionTable selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MissionTable record, @Param("example") MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MissionTable record, @Param("example") MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MissionTable record, @Param("example") MissionTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MissionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MissionTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table missiontable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MissionTable record);
}